import { createTypes } from 'reduxsauce'

export default createTypes(`
    FETCH_MENU_OPTIONS,
    FETCH_ABOUT_ME,
    FETCH_COMPLETED_PROJECTS
    FETCH_PENDING_PROJECTS
    FETCH_POSTS
    FETCH_GOOD_READS

    STORE_MENU_OPTIONS,
    STORE_ABOUT_ME,
    STORE_COMPLETED_PROJECTS
    STORE_PENDING_PROJECTS
    STORE_POSTS
    STORE_GOOD_READS
`)